### PR TITLE
More data model tests

### PR DESCRIPTION
**Pull request by umbernhard**

### CODE REVIEW

**Review by vteague — APPROVED** [review]
Looks good, thanks - I'll assume you discussed with @charliecarlton how to do the clock that's only used for testing. (I think I would have had an "#IF TESTING...." sort of style rather than a null-check, but if you & charlie are happy with that structure, then great.
I'll leave this open for a few days in case @charliecarlton would like to comment.

**Comment by cjcarlton** [comment]
I believe I follow the logic with the clock but agree a comment near the null checks could be helpful.  otherwise, LGTM

**Comment by umbernhard** [comment]
I will submit a revised version with comments tomorrow! Thanks for the helpful feedback!

**Comment by umbernhard** [comment]
Okay, revised with comments. @charliecarlton if you approve then @vteague can merge.

**Review by cjcarlton — APPROVED** [review]
looks good!

**Pull request merged**
