### PR TITLE
Demo extras

### PR DESCRIPTION
**Pull request by vteague**
This cleans up the demo and adds the audit init.

### CODE REVIEW

**Review by cjcarlton — COMMENTED** [review]
I've run all the tests and they all look great except, for some reason, I have a couple failures in the final county-2-Alamosa-do-audit.http:

**GET http://localhost:8888/cvr-to-audit-list?round=1:**
with the error:
TypeError: Cannot read property "cvr_number" from undefined
  jsHandler (at C:\work\DemocracyDevelopers\colorado-rla\server\eclipse-project\src\test\workflows\county-2-Alamosa-do-audit.http:54)

AND

**GET http://localhost:8888/cvr/id/{{cvr_id}}**
with the error:
TypeError: Cannot read property "0" from undefined
  jsHandler (at C:\work\DemocracyDevelopers\colorado-rla\server\eclipse-project\src\test\workflows\county-2-Alamosa-do-audit.http:77)

Quite possible I'm doing something incorrect here so please let me know!

Another small thing we could do is put the test/workflows directory into .gitignore

Otherwise it LGTM and is really nice to have these tests!

**Comment by vteague** [comment]
Are you running everything with the 'dev' environment? I forgot to add that instruction to the README, but have done so now. Nevertheless, I don't think that would be causing the problem you're seeing.

**Comment by vteague** [comment]
@charliecarlton try
- make sure you're in the 'dev' environment
- start from the start again (clean out the database etc)
- load in all the manifests and cvrs (Boulder_loadCVRs, Boulder_loadManifest, demo1_loadCVRs, demo1_loadManifests)
- run demo1_defineAudit, making sure you're in 'dev' environment. Look carefully for errors in the console - I'm afraid the tests can 'pass' even if not quite the expected thing happened. 
- now try county-2-Alamosa-do-audit.

**Comment by vteague** [comment]
@charliecarlton I'm hoping your issues were caused by the same reason as @michelleblom 's issues, which she fixed. Try pulling the update and running again. I'll also update the README to make some things clearer.

**Comment by vteague** [comment]
@charliecarlton this is finally ready for re-review! I've disabled Demo1, but it works fine as long as you have the server running.

**Review by cjcarlton — APPROVED** [review]
looks good!

**Pull request merged**
